### ISSUE TITLE
Публикация сайта

### ISSUE THREAD

**Issue by ForNeVeR** [fsharplang-ru/fsharplang.ru#1]
1. Будем ли мы хостить сайт на GitHub pages или как-то ещё?
2. GitHub Pages из коробки поддерживает только Jekyll. Будем ли мы готовить страницы каким-то другим способом?
3. @Neftedollar упоминал, что хочется использовать Fable. Каким образом? Как видится сценарий билда и публикации при этом?

**Comment by Neftedollar** [comment]
1. Думаю разделить. Хоститить сам сайт на vps/docker whatever. А блог сделать на gh pages доступным для pull request'ов.
2. Не знаю про jekyll, надо посмотреть,. Думал про FsBlog.
3. Fable можно использовать для той части сайта, которая не общедоступная для pull request'ов. Типа генерация лога из телеграм и т.д.
@ForNeVeR

**Comment by ForNeVeR** [comment]
> Думаю разделить. Хоститить сам сайт на vps/docker whatever. А блог сделать на gh pages доступным для pull request'ов.

Я вот хотел возразить, но немного обдумал это, и мне кажется это хорошей идеей. Только вот как мы будем объединять эти части? Основной сайт будет показывать постинги в iframe со своим оформлением, или как? Надо продумать этот момент.

> Не знаю про jekyll, надо посмотреть,. Думал про FsBlog.

В принципе, можно генерировать статические страницы чем угодно, и заливать в отдельный бранч gh-pages. Это работает.

Вообще, сколько у нас будет разных частей на сайте? Я думаю, надо оформить по ишую на каждую часть, которую мы хотим сделать: 1) логи из телеграма, 2) основной лендинг, 3) материалы / посты.

И я пока что не понял, как мы их будем объединять.

**Comment by Neftedollar** [comment]
>Только вот как мы будем объединять эти части? 

Проксируем на gh.pages тут все просто.
То же самое и с объединением остальных частей. 
Сколько их будет пока думал про эти три. Но как всегда надо готовится к тому что их будет и больше)

**Comment by Neftedollar** [comment]
готово
