### ISSUE TITLE
Смержить сюда fsharplang-ru.github.io

### ISSUE THREAD

**Issue by ForNeVeR** [fsharplang-ru/fsharplang.ru#2]
Я предлагаю объединить проекты https://github.com/fsharplang-ru/fsharplang.ru и https://github.com/fsharplang-ru/fsharplang-ru.github.io

Второй сам по себе не имеет никакого смысла: мы всё равно собираемся содержимое оттуда выкладывать на основной сайт.

**Comment by Neftedollar** [comment]
как раз планируется чтоб эти репозитории были разделены, но пока что в https://github.com/fsharplang-ru/fsharplang-ru.github.io лежит placeholder для сайта. Потом туда будем складывать общедоступные для публикации и pull request'ов  материалы.

**Comment by ForNeVeR** [comment]
Ок, понял. Тогда пока что пожелание отзываю.
