### ISSUE TITLE
Логи чата

### ISSUE THREAD

**Issue by ForNeVeR** [fsharplang-ru/fsharplang.ru#3]
Нам нужно какое-то доступное онлайн хранилище для логов нашего Телеграм-чата. Причём подключить его предлагаю как можно скорее в хотя бы каком-то убогом виде (потом сконвертируем на новую платформу, если она будет). Новые люди всё поступают и пишут умные вещи — не хотелось бы их мысли потерять :)

**Comment by FoggyFinder** [comment]
Жду с нетерпением - очень уж хочется почитать историю :)

**Comment by worldbeater** [comment]
Эти данные в будущем можно распарсить в формат вопрос-ответ и запилить FAQ-сервис про Ф# типа Тостера без смс и регистрации. 🎉🎇✨

**Comment by Neftedollar** [comment]
как обещал скрипт для парсинга чата
>вот этим скриптом https://github.com/tvdstaaij/telegram-history-dump (для него еще нужен вот такой https://github.com/vysheng/tg )

**Comment by ForNeVeR** [comment]
Господа, у меня получилось ценой некоторых усилий наконвертировать логи на сегодняшний момент: https://fornever.me/app/fsharp/FSharpChat-0.html

Использовал указанный выше скрипт на Ruby, для этого пришлось собрать `telegram-cli` и конвертовать всё внутри WSL.

Есть логи в JSON и в HTML, в любой момент в будущем можно будет наконвертировать ещё.

В связи с этим ещё несколько вопросов:

1. Как бы нам подключить их к сайту?
2. Что будем делать дальше? Я могу собрать свой способ конвертации куда-нибудь в Docker и ежедневно прогонять, но как-то кривовато это всё, да и проводить можно только разовые акции (нельзя формировать логи в реальном времени).

Предлагаю:
- изучить JSON-формат, в котором скрипт хранит логи, и импортировать в SQL-базу
- написать бота на F#, которого подсадим в чат, и чтобы он все логи в будущем сохранял в ту же базу
- посадить это всё в Docker на .NET Core, и засервить где-нибудь (могу предложить у себя: у меня есть линуксовая машина, она достаточно надёжная и никогда не выключается, но я не настоящий девопс и 100% надёжности работы не обещаю)

**Comment by Neftedollar** [comment]
С ботом согласен.
Раз есть json зачем выдумывать? Давайте запихнем все в монгу. 
С докером согласен.

**Comment by ForNeVeR** [comment]
Можно и в монгу, просто я в неё не умею, например. Но можно и потренироваться, чего бы и нет!

**Comment by Neftedollar** [comment]
@ForNeVeR  там хорошая документация для .net. И есть большой плюс в том, что, можно подключиться к БД как к реплике и например через вебсокеты отправлять изменения на клиентам. Так напрмиер работает meteorjs.

**Comment by Neftedollar** [comment]
закрыто тут
https://github.com/fsharplang-ru/fsharplang-ru.github.io/issues/18
