### ISSUE TITLE
Продумать редакционную политику

### ISSUE THREAD

**Issue by ForNeVeR** [fsharplang-ru/fsharplang.ru#6]
Всем известно, что мы сотрудничаем с [официальным сообществом Microsoft](https://habrahabr.ru/company/microsoft/) на Хабрахабре и частенько публикуем материалы туда. Я считаю, что это очень хорошая идея, которая способствует популяризации языка у крупной аудитории ресурса. Однако, у Хабрахабра есть [правила](https://habrahabr.ru/info/help/rules/), в соответствии с которыми не допускается перепубликация там материалов, которые ранее были опубликованы в другом месте.

Если мы хотим начать публиковать статьи у себя (см. #4, #5), но при этом не хотим прекращать публиковать их на Хабре (необязательно в блог MS), нам нужно выработать соответствующую политику: в каком порядке будем осуществлять публикацию. Например, можно предложить такой workflow:

1. Работаем над статьёй совместно на github в отдельной ветке (не публикуя на сайт).
2. Открываем PR, проводим финальный ревью.
3. Публикуем на Хабрахабр.
4. Через сутки можем публиковать у себя.

С таким предложением есть некоторые вопросы (скажем, не будет ли выкладывание текста статьи в отдельной ветке на github считаться «публикацией» по правилам Хабрахабра). Вероятно, мне стоит написать письмо в саппорт и просто выяснить у них эти подробности?

**Comment by FoggyFinder** [comment]
> С таким предложением есть некоторые вопросы (скажем, не будет ли выкладывание текста статьи в отдельной ветке на github считаться «публикацией» по правилам Хабрахабра). Вероятно, мне стоит написать письмо в саппорт и просто выяснить у них эти подробности?

Да, хотелось бы прояснить этот момент

**Comment by Neftedollar** [comment]
Плюсую. Можешь написать им?
Если будешь писать через почту поставь в копию плз
iam at neftedollar dot com

**Comment by ForNeVeR** [comment]
Ок, ребят, если принципиальных возражений по такому workflow нет, то напишу в саппорт хабра.

**Comment by ForNeVeR** [comment]
Отправил запрос через форму поддержки хабра, будем ждать ответа.

**Comment by ForNeVeR** [comment]
Вот что мне пишет поддержка Хабра:

> 1. Подготовка текста в общедоступном GitHub-репозитории может быть расценена модераторами как нарушение процитированного вами правила, поэтому лучше не рисковать и использовать инструмент коллективной работы не находящийся в общем доступе, например, Google Docs.
>
> 2. После размещения материала на Хабре его можно смело размещать на других ресурсах уже через 5 минут.

Плюс, я уточнил немного про поисковые индексы. Насколько я смог определить, пул-реквесты на github и их содержимое не индексируются поисковиками (что соответствует содержимому `robots.txt` гитхаба).

В итоге, гм, ответы неоднозначные, давайте думать и принимать решение!

**Comment by ForNeVeR** [comment]
От себя могу добавить, что практика приватного ревью статей пока зарекомендовала себя не с лучшей стороны: люди имеют склонность забыть про то, что обещали поревьюить статью. Если бы она висела в списке пул-реквестов и каждый бы мог её посмотреть, дело бы двигалось быстрее, я думаю.

Есть предложение всё-таки использовать модель github и пул-реквесты для обсуждения новых статей, но при этом просить авторов, чтобы они не делали пул-реквестов из ветки `master` (при соблюдении этого условия наш материал будет невидим для поисковиков до момента слияния, и тем самым мы не навредим поисковому рейтингу хабра, т.е. поступим добросовестно).

**Comment by FoggyFinder** [comment]
> Подготовка текста в общедоступном GitHub-репозитории **может быть** расценена модераторами как нарушение процитированного вами правила

Нет, чтобы четко сказать - да или нет =)

---

Есть еще GitLab где, насколько мне известно, приватные репозитории предостовлются бесплатно. Тогда точно никаких правил нарушатся не будет. Из "-" - не у всех там есть профиль.

**Comment by ForNeVeR** [comment]
Ну, в общем, да, мы с @Neftedollar сейчас обсуждаем возможность интегрироваться как-то с GitLab.

Я лично пока вижу примерно такую схему:

- делаем организацию на гитлаб, куда приглашаем всех подряд
- переводы и новые материалы просим приватно пилить на гитлабе
- там же ревьюим, мержим
- когда приходит время публиковаться у себя — ответственное лицо пулит с гитлаба и пушит в гитхаб
- каждый раз, когда требуется ревью или помощь с материалами — всегда кидаем клич в чатики и сюда в issues со ссылками на гитлаб и инструкциями по присоединению, чтобы все потенциальные ревьюеры были в курсе

С одной стороны, гитхаб нам получается не очень-то нужен в такой схеме, но при этом он всё-таки даёт большие бонусы к социальной составляющей (всякие там звёздочки, фолловеры и пр.), так что я считаю, что нам __обязательно__ нужно продолжать тут светиться и кипишевать.

Схема получается, гм, не очень удобная, но рабочая. Ждём других предложений.
